"""
VBAGenerator - Convert high-level commands to VBA macros

Responsible for:
- Template-based VBA generation
- Parameter substitution
- Error handling macros
- Macro validation
"""

from typing import Dict, Any, List
from utils.logger import get_logger


logger = get_logger(__name__)


class VBAGenerator:
    """Generate VBA macro code from commands"""
    
    # Simple VBA templates for each command type
    TEMPLATES = {
        "create_project": """
Set objCST = CreateObject("CSTStudio.Application")
objCST.NewMWS {name}
""",
        "set_units": """
objMWS.Unit("{units}")
""",
        "set_frequency_range": """
objMWS.Frequency({freq_start}, {freq_stop})
""",
        "define_material": """
With objMWS.Material("{material_name}")
    .Epsilon = {epsilon}
    .TanDelta = {tan_delta}
End With
""",
        "create_substrate": """
With objMWS.Component("Substrate")
    .Width = {width}
    .Length = {length}
    .Height = {height}
    .Material = "{material}"
End With
""",
        "create_patch": """
With objMWS.Component("Patch")
    .Width = {width}
    .Length = {length}
    .Height = {height}
    .Material = "{material}"
    .XPos = {x_pos}
    .YPos = {y_pos}
    .ZPos = {z_pos}
End With
""",
        "create_port": """
With objMWS.Port("{port_name}")
    .Type = "{port_type}"
    .XPos = {x_pos}
    .YPos = {y_pos}
    .ZPos = {z_pos}
    .Impedance = {impedance}
End With
""",
        "run_solver": """
objMWS.Solver.FrequencyRange("{freq_start}", "{freq_stop}")
objMWS.Solver.Run
"""
    }
    
    def generate_macro(self, command_type: str, parameters: Dict[str, Any]) -> str:
        """Generate VBA macro for command
        
        Args:
            command_type: Type of command
            parameters: Command parameters dict
            
        Returns:
            VBA code as string
            
        Raises:
            ValueError: If command type not supported
        """
        if command_type not in self.TEMPLATES:
            raise ValueError(f"Unsupported command type: {command_type}")
        
        template = self.TEMPLATES[command_type]
        
        try:
            # Substitute parameters into template
            macro_code = template.format(**parameters)
            logger.debug(f"Generated macro for {command_type}")
            return macro_code
        except KeyError as e:
            logger.error(f"Missing parameter for {command_type}: {e}")
            raise ValueError(f"Missing required parameter: {e}")
    
    def generate_package_script(self, commands_code: List[str]) -> str:
        """Generate complete VBA script from multiple macros
        
        Args:
            commands_code: List of macro code strings
            
        Returns:
            Complete VBA script
        """
        script = "' Auto-generated VBA script for antenna design\n"
        script += "' Generated by Antenna Optimization Client\n\n"
        script += f"Option Explicit\n"
        script += f"Dim objCST\n"
        script += f"Dim objMWS\n\n"
        script += f"' Initialize CST\n"
        script += f"Set objCST = CreateObject(\"CSTStudio.Application\")\n"
        script += f"Set objMWS = objCST.ActiveMWS\n\n"
        script += f"On Error GoTo ErrorHandler\n\n"
        script += f"' Execute commands\n"
        for i, cmd in enumerate(commands_code, 1):
            script += f"' Command {i}\n"
            script += f"{cmd}\n\n"
        
        script += f"""
Exit Sub
ErrorHandler:
    MsgBox "Error " & Err.Number & ": " & Err.Description
End Sub
"""
        return script
    
    def validate_macro(self, macro_code: str) -> bool:
        """Validate VBA macro syntax (basic check)
        
        Args:
            macro_code: VBA code to validate
            
        Returns:
            True if appears valid
        """
        # Basic sanity checks
        checks = [
            "Sub" not in macro_code,  # Not a full procedure
            len(macro_code) > 0,
            "With" not in macro_code or "End With" in macro_code,  # Balanced With statements
        ]
        return all(checks)


class VBATemplateManager:
    """Manage VBA templates for custom commands"""
    
    def __init__(self, template_dir: str = "executor/templates"):
        """Initialize template manager
        
        Args:
            template_dir: Directory containing .vba template files
        """
        self.template_dir = template_dir
        self.templates = {}
        logger.info(f"VBATemplateManager initialized with dir: {template_dir}")
    
    def load_template(self, command_type: str) -> str:
        """Load VBA template for command type
        
        Args:
            command_type: Command type (e.g., 'create_patch')
            
        Returns:
            Template content as string
            
        Raises:
            FileNotFoundError: If template not found
        """
        file_path = f"{self.template_dir}/cmd_{command_type}.vba"
        try:
            with open(file_path, 'r') as f:
                template = f.read()
            self.templates[command_type] = template
            logger.debug(f"Loaded template for {command_type}")
            return template
        except FileNotFoundError:
            logger.error(f"Template not found: {file_path}")
            raise
